# Generated by Django 3.0.7 on 2020-06-05 11:04

import candidates.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.rename_and_save, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
