# Generated by Django 3.0.7 on 2020-06-05 15:47

import candidates.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='job_applied_to',
            field=models.CharField(choices=[('Backend Engineer', 'Backend Engineer'), ('Frontend Engineer', 'Frontend Engineer'), ('Python Developer', 'Python Developer'), ('Business Analyst', 'Business Analyst'), ('ML Engineer', 'ML Engineer'), ('Data Engineer', 'Data Engineer'), ('Technical Recruiter', 'Technical Recruiter')], max_length=100),
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='candidatemodel',
            name='resume',
            field=models.FileField(null=True, upload_to=candidates.models.rename_and_save, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx'])]),
        ),
    ]
