# Generated by Django 3.0.7 on 2020-06-06 11:50

import candidates.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_auto_20200605_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemodel',
            name='resume',
            field=models.FileField(null=True, upload_to=candidates.models.rename_and_save, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'docx'])]),
        ),
    ]
